### ISSUE TITLE
No Class Found errors

### ISSUE THREAD

**Issue by wingzero54** [CivMC/KiraBukkitGateway#4]
Getting this error a lot, not sure if it is a network issue or code issue

[07:23:00] [pool-41-thread-5/INFO]: [KiraBukkitGateway] [STDOUT]  [x] Received 'sendgroupmessage {"sender"xxxx","message":"xxxx","group":"xxxx"}'
[07:23:00] [pool-41-thread-5/ERROR]: [com.rabbitmq.client.impl.ForgivingExceptionHandler] Consumer com.rabbitmq.client.impl.recovery.AutorecoveringChannel$2@xxxxx (xxxxx) method handleDelivery for channel AMQChannel(amqp://rabbitmq@xxxxxx) threw an exception for channel AMQChannel(amqp://rabbitmq@xxxxx)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/entity/CraftPlayer
	at com.github.maxopoly.KiraBukkitGateway.rabbit.in.GroupChatMessageHandler.handle(GroupChatMessageHandler.java:24) ~[KiraBukkitGateway-2.0.0-SNAPSHOT.jar:?]
	at com.github.maxopoly.KiraBukkitGateway.rabbit.RabbitInputHandler.handle(RabbitInputHandler.java:58) ~[KiraBukkitGateway-2.0.0-SNAPSHOT.jar:?]
	at com.github.maxopoly.KiraBukkitGateway.rabbit.RabbitHandler$1.lambda$run$0(RabbitHandler.java:55) ~[KiraBukkitGateway-2.0.0-SNAPSHOT.jar:?]
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$2.handleDelivery(AutorecoveringChannel.java:577) ~[KiraBukkitGateway-2.0.0-SNAPSHOT.jar:?]
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) ~[KiraBukkitGateway-2.0.0-SNAPSHOT.jar:?]
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) ~[KiraBukkitGateway-2.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer

**Comment by Diet-Cola** [comment]
https://github.com/CivMC/KiraBukkitGateway/tree/1.18.2

Starting work on this here

**Comment by Diet-Cola** [comment]
Fixed by https://github.com/CivMC/KiraBukkitGateway/pull/5
